config/routes.rb
Rails.application.routes.draw do
  resources :expenses
  resources :foods
  resources :houses
  resources :profiles

end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :profile
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :profile
end

app/models/house.rb
class House < ActiveRecord::Base
  belongs_to :profile
end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:profile_id, :clothing, :healthcare, :vehicle, :home_maintenance)
    end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:profile_id, :red_meat, :poultry, :seafood, :vegetables, :milk, :other_drinks)
    end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show, :edit, :update, :destroy]

  # GET /houses
  # GET /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to @house, notice: 'House was successfully created.' }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url, notice: 'House was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:house).permit(:profile_id, :electricity, :fuel, :gas, :water)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:firstname, :lastname, :age, :country, :state, :city, :zipcode)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/expenses/_form.html.erb
<%= simple_form_for(@expense) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :profile %>
    <%= f.input :clothing %>
    <%= f.input :healthcare %>
    <%= f.input :vehicle %>
    <%= f.input :home_maintenance %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing Expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Expenses</h1>

<table>
  <thead>
    <tr>
      <th>Profile</th>
      <th>Clothing</th>
      <th>Healthcare</th>
      <th>Vehicle</th>
      <th>Home maintenance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.profile %></td>
        <td><%= expense.clothing %></td>
        <td><%= expense.healthcare %></td>
        <td><%= expense.vehicle %></td>
        <td><%= expense.home_maintenance %></td>
        <td><%= link_to 'Show', expense %></td>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/new.html.erb
<h1>New Expense</h1>

<%= render 'form' %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Profile:</strong>
  <%= @expense.profile %>
</p>

<p>
  <strong>Clothing:</strong>
  <%= @expense.clothing %>
</p>

<p>
  <strong>Healthcare:</strong>
  <%= @expense.healthcare %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @expense.vehicle %>
</p>

<p>
  <strong>Home maintenance:</strong>
  <%= @expense.home_maintenance %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/foods/_form.html.erb
<%= simple_form_for(@food) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :profile %>
    <%= f.input :red_meat %>
    <%= f.input :poultry %>
    <%= f.input :seafood %>
    <%= f.input :vegetables %>
    <%= f.input :milk %>
    <%= f.input :other_drinks %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Foods</h1>

<table>
  <thead>
    <tr>
      <th>Profile</th>
      <th>Red meat</th>
      <th>Poultry</th>
      <th>Seafood</th>
      <th>Vegetables</th>
      <th>Milk</th>
      <th>Other drinks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.profile %></td>
        <td><%= food.red_meat %></td>
        <td><%= food.poultry %></td>
        <td><%= food.seafood %></td>
        <td><%= food.vegetables %></td>
        <td><%= food.milk %></td>
        <td><%= food.other_drinks %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Profile:</strong>
  <%= @food.profile %>
</p>

<p>
  <strong>Red meat:</strong>
  <%= @food.red_meat %>
</p>

<p>
  <strong>Poultry:</strong>
  <%= @food.poultry %>
</p>

<p>
  <strong>Seafood:</strong>
  <%= @food.seafood %>
</p>

<p>
  <strong>Vegetables:</strong>
  <%= @food.vegetables %>
</p>

<p>
  <strong>Milk:</strong>
  <%= @food.milk %>
</p>

<p>
  <strong>Other drinks:</strong>
  <%= @food.other_drinks %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>

app/views/houses/_form.html.erb
<%= simple_form_for(@house) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :profile %>
    <%= f.input :electricity %>
    <%= f.input :fuel %>
    <%= f.input :gas %>
    <%= f.input :water %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/houses/edit.html.erb
<h1>Editing House</h1>

<%= render 'form' %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Houses</h1>

<table>
  <thead>
    <tr>
      <th>Profile</th>
      <th>Electricity</th>
      <th>Fuel</th>
      <th>Gas</th>
      <th>Water</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.profile %></td>
        <td><%= house.electricity %></td>
        <td><%= house.fuel %></td>
        <td><%= house.gas %></td>
        <td><%= house.water %></td>
        <td><%= link_to 'Show', house %></td>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New House', new_house_path %>

app/views/houses/new.html.erb
<h1>New House</h1>

<%= render 'form' %>

<%= link_to 'Back', houses_path %>

app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Profile:</strong>
  <%= @house.profile %>
</p>

<p>
  <strong>Electricity:</strong>
  <%= @house.electricity %>
</p>

<p>
  <strong>Fuel:</strong>
  <%= @house.fuel %>
</p>

<p>
  <strong>Gas:</strong>
  <%= @house.gas %>
</p>

<p>
  <strong>Water:</strong>
  <%= @house.water %>
</p>

<%= link_to 'Edit', edit_house_path(@house) %> |
<%= link_to 'Back', houses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :firstname %>
    <%= f.input :lastname %>
    <%= f.input :age %>
    <%= f.input :country %>
    <%= f.input :state %>
    <%= f.input :city %>
    <%= f.input :zipcode %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Age</th>
      <th>Country</th>
      <th>State</th>
      <th>City</th>
      <th>Zipcode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.firstname %></td>
        <td><%= profile.lastname %></td>
        <td><%= profile.age %></td>
        <td><%= profile.country %></td>
        <td><%= profile.state %></td>
        <td><%= profile.city %></td>
        <td><%= profile.zipcode %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @profile.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @profile.lastname %>
</p>

<p>
  <strong>Age:</strong>
  <%= @profile.age %>
</p>

<p>
  <strong>Country:</strong>
  <%= @profile.country %>
</p>

<p>
  <strong>State:</strong>
  <%= @profile.state %>
</p>

<p>
  <strong>City:</strong>
  <%= @profile.city %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @profile.zipcode %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>